CREATE DATABASE IF NOT EXISTS AULAS1316;
USE AULAS1316;

CREATE TABLE IF NOT EXISTS CARGO (
 id LONG NOT NULL,
 nome VARCHAR(255) NOT NULL,
 salario DOUBLE NOT NULL,
 PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
 id LONG NOT NULL,
 nome VARCHAR(255) NOT NULL,
 PRIMARY KEY (id));
 
 CREATE TABLE IF NOT EXISTS FUNCIONARIO (
 id LONG NOT NULL,
 nome VARCHAR(255) NOT NULL,
 matricula LONG NOT NULL,
 PRIMARY KEY (id));
 
 CREATE TABLE IF NOT EXISTS LOTACAO (
 id LONG NOT NULL,
 dataInicial DATE NOT NULL,
 dataFinal DATE,
 idCargo VARCHAR(20) NOT NULL,
 idDepartamento VARCHAR(20) NOT NULL,
 PRIMARY KEY (id),
 FOREIGN KEY (`idCargo`)
 REFERENCES `AULAS1316`.`CARGO` (`id`),
 FOREIGN KEY (`idDepartamento`)
 REFERENCES `AULAS1316`.`DEPARTAMENTO` (`id`));